### ISSUE TITLE
Add an alphabetical index menu and size setting

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [mondeja/simple-icons-blender#11]
This menu is too long. It's hard to find the icon you need.
Add an alphabetical index menu that can help us get what we need quickly

```
add icon/
         A/
           Apple
           ASUS
           Azure
           ...
         B/
           Bob
           BOSS
           ...
         ...
```

And I think a default size setting (Default scale size) should be added, just like the official created object
![image](https://github.com/mondeja/simple-icons-blender/assets/65578116/c6021205-c2ba-4319-a69f-65033e9d75bf)

**Comment by mondeja** [comment]
These features have been released in [v9.8.0](https://github.com/mondeja/simple-icons-blender/releases/tag/9.8.0), thanks for the suggestions.
